repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.6
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: main
    hooks:
      - id: ruff
        entry: uv run ruff check
        language: system
      - id: ruff-format
        entry: uv run ruff format
        language: system
  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: uv run pytest
      language: system
      types: [python]
      pass_filenames: false
      always_run: true