name: Run Checks
on:
  pull_request:
    branches:
      - main
jobs:
  commands-test:
    runs-on:  ubuntu-latest
    strategy:
      matrix:
        python_versions: [ "3.8", "3.9", "3.10", "3.11", "3.12", "3.13" ]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_versions }}

      - name: Install Dependencies
        run: |
          uv sync --all-extras --dev

      - name: Run Pytest
        run: uv run pytest

  dynamic-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, debian-11, fedora-36, centos-8]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install Dependencies
        run: |
          uv sync --all-extras --dev

      - name: Test Commands on Multi Operating Systems
        run: uv run pytest ./tests/dynamic_tests.py
